FROM golang:1.12 as builder

WORKDIR /home/yahe-auth

COPY . .
RUN make build



FROM alpine:3.9

WORKDIR /home/yahe-auth
COPY entrypoint.sh /
RUN chmod 755 /entrypoint.sh && adduser -D yahe-auth

COPY config.auth.base.yaml /etc/yaheauth/config.yaml

USER yahe

COPY --from=builder /home/yahe-auth/bin/yahe-auth .

EXPOSE 8080
ENTRYPOINT ["/entrypoint.sh", "/home/yahe-auth/yahe-auth"]
CMD ["api", "serve"]
